name: Test

on:
  push:
    paths:
      - "packages/**"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "packages/**"
      - ".github/workflows/test.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

      - name: Install
        run: npm install

      - name: Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').packages['node_modules/playwright'].version)")" >> $GITHUB_ENV

      - name: Cache Playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: "~/.cache/ms-playwright"
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Test
        id: test
        continue-on-error: true
        run: npm test

      - name: Uploading screenshots on failure
        if: steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: failure-screenshots
          path: packages/storybook/test-results

      - name: Exit signal
        if: steps.test.outcome == 'failure'
        run: exit 1
